Add support for fetching rules for multiple tenants
observatorium/thanos-rule-syncer pull request #8
Opened 2021-12-23 11:37 UTC by onprem

Fixes #7 

- [x] Add basic support for fetching rules for multiple tenants.
- [x] DO networks requests to fetch rules concurrently.
- [ ] Handle tenants with invalid configuration gracefully.
- [ ] Instrument skipped/failed tenants with metrics.

Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>

2021-12-23 11:50 UTC, squat commented on main.go
> +					// TODO(onprem): Handle errors.
This seems actually pretty crucial. Getting the rules is the core functionality of this whole project; if this fails, we need to know and retry. I think we should address this :+1:

2021-12-30 12:06 UTC, ianbillett requested changes
Sorry to block @onprem but I feel quite strongly that we should not be handling, storing or using any user's secret material in this component.

As a sidecar in Ruler, `thanos-ruler-syncer` is already part of a component that communicates directly with the thanos backends and bypasses API auth. It is acceptable for `thanos-ruler-syncer` to do the same.

If `rules-objstore` exposed a `ListAllRules` endpoint, `thanos-ruler-syncer` could call that to get the rules. As the API enforces tenant headers, we could return all rules when the tenant header is not set? 

That is less than ideal, but is a preferable problem to have than managing user secret material.

2022-01-03 10:26 UTC, onprem commented
> If rules-objstore exposed a ListAllRules endpoint, thanos-ruler-syncer could call that to get the rules. As the API enforces tenant headers, we could return all rules when the tenant header is not set?

The rules backend utilises URL path parameters instead of tenant header (i.e `/api/v1/<tenant-name>/rules` ) but we can just create another endpoint that lists all rules.

I agree with your point that Rule Syncer is internal and it would be better to skip Obs API auth.

2022-01-11 12:32 UTC, onprem commented
Closing in favor of #9

2022-01-11 12:32 UTC, closed without merging